# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://mnd-bootstrap.herokuapp.com
encoding:         UTF-8

# Custom vars
current_version:  3.1.1
repo:             https://github.com/mynewsdesk/mnd-bootstrap
sass_repo:        https://github.com/mynewsdesk/mnd-bootstrap

download:
  source:         https://github.com/mynewsdesk/mnd-bootstrap
  dist:           https://github.com/mynewsdesk/mnd-bootstrap
  sass:           https://github.com/mynewsdesk/mnd-bootstrap

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js
